#include "vm.h"

// Bytecode utilities
const char* opcode_name(opcode op) {
    switch (op) {
    case OP_PUSH_CONSTANT:
        return "PUSH_CONSTANT";
    case OP_PUSH_NULL:
        return "PUSH_NULL";
    case OP_PUSH_UNDEFINED:
        return "PUSH_UNDEFINED";
    case OP_PUSH_TRUE:
        return "PUSH_TRUE";
    case OP_PUSH_FALSE:
        return "PUSH_FALSE";
    case OP_POP:
        return "POP";
    case OP_DUP:
        return "DUP";
    case OP_SWAP:
        return "SWAP";
    case OP_NIP:
        return "NIP";
    case OP_ROT:
        return "ROT";
    case OP_OVER:
        return "OVER";
    case OP_SET_RESULT:
        return "SET_RESULT";
    case OP_ADD:
        return "ADD";
    case OP_SUBTRACT:
        return "SUBTRACT";
    case OP_MULTIPLY:
        return "MULTIPLY";
    case OP_DIVIDE:
        return "DIVIDE";
    case OP_MOD:
        return "MOD";
    case OP_POWER:
        return "POWER";
    case OP_NEGATE:
        return "NEGATE";
    case OP_EQUAL:
        return "EQUAL";
    case OP_NOT_EQUAL:
        return "NOT_EQUAL";
    case OP_LESS:
        return "LESS";
    case OP_LESS_EQUAL:
        return "LESS_EQUAL";
    case OP_GREATER:
        return "GREATER";
    case OP_GREATER_EQUAL:
        return "GREATER_EQUAL";
    case OP_NOT:
        return "NOT";
    case OP_AND:
        return "AND";
    case OP_OR:
        return "OR";
    case OP_NULL_COALESCE:
        return "NULL_COALESCE";
    case OP_IN:
        return "IN";
    case OP_INSTANCEOF:
        return "INSTANCEOF";
    case OP_BITWISE_AND:
        return "BITWISE_AND";
    case OP_BITWISE_OR:
        return "BITWISE_OR";
    case OP_BITWISE_XOR:
        return "BITWISE_XOR";
    case OP_BITWISE_NOT:
        return "BITWISE_NOT";
    case OP_LEFT_SHIFT:
        return "LEFT_SHIFT";
    case OP_RIGHT_SHIFT:
        return "RIGHT_SHIFT";
    case OP_LOGICAL_RIGHT_SHIFT:
        return "LOGICAL_RIGHT_SHIFT";
    case OP_FLOOR_DIV:
        return "FLOOR_DIV";
    case OP_INCREMENT:
        return "INCREMENT";
    case OP_DECREMENT:
        return "DECREMENT";
    case OP_GET_LOCAL:
        return "GET_LOCAL";
    case OP_SET_LOCAL:
        return "SET_LOCAL";
    case OP_GET_GLOBAL:
        return "GET_GLOBAL";
    case OP_SET_GLOBAL:
        return "SET_GLOBAL";
    case OP_DEFINE_GLOBAL:
        return "DEFINE_GLOBAL";
    case OP_GET_PROPERTY:
        return "GET_PROPERTY";
    case OP_SET_PROPERTY:
        return "SET_PROPERTY";
    case OP_BUILD_ARRAY:
        return "BUILD_ARRAY";
    case OP_SET_INDEX:
        return "SET_INDEX";
    case OP_BUILD_OBJECT:
        return "BUILD_OBJECT";
    case OP_BUILD_RANGE:
        return "BUILD_RANGE";
    case OP_CLOSURE:
        return "CLOSURE";
    case OP_CALL:
        return "CALL";
    case OP_RETURN:
        return "RETURN";
    case OP_JUMP:
        return "JUMP";
    case OP_JUMP_IF_FALSE:
        return "JUMP_IF_FALSE";
    case OP_JUMP_IF_TRUE:
        return "JUMP_IF_TRUE";
    case OP_LOOP:
        return "LOOP";
    case OP_POP_N:
        return "POP_N";
    case OP_POP_N_PRESERVE_TOP:
        return "POP_N_PRESERVE_TOP";
    case OP_SET_DEBUG_LOCATION:
        return "SET_DEBUG_LOCATION";
    case OP_CLEAR_DEBUG_LOCATION:
        return "CLEAR_DEBUG_LOCATION";
    case OP_HALT:
        return "HALT";
    default:
        return "UNKNOWN";
    }
}